application: sibalumniportal
version: 3
runtime: python27
api_version: 1
threadsafe: false

libraries:                                                                      
- name: jinja2                                                                  
  version: latest                                                               
- name: markupsafe                                                              
  version: latest  

## Uncomment to enable App Engine appstats
# builtins:
# - appstats: on

handlers:

- url: /.*favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico
  expiration: 0

- url: /images
  static_dir: images

- url: /css
  static_dir: css

- url: /feed
  script: main.py
  login: required

- url: /.*
  script: main.py
